### PR TITLE
Refactor Registration Form and Implement Input Checks

### PR DESCRIPTION
**Pull request by kirtiraj22**
## Description : 

**Updated the registration form to match the design using the "react-hook-form" library.**

### Tasks Completed:
1. Refactored the whole registration page
2. Implemented checks for each form field.
3. Integrated the provided image on the left.
4. Added the ability to show/hide passwords.
5. Ensured all required fields are included.
6. added and used react-form-library (so that we can use it in other forms too)
7. Tested the form using multiple test cases 

## Remaining Tasks:
- [ ] Make the page responsive.
- [ ] Implement dynamic password check (Upper Case, Lower Case, One Number, 8 Characters) - A separate issue can be created for it. 
- [ ] Although the Privacy Policy section isn't added visually, the check is in place.

### Notes:
- The page's responsiveness and dynamic password check can be addressed in upcoming updates.
- the privacy policy check works fine only the data(terms and conditions) needs to be added 

### GIF : 
e0e03566-21e9-4209-af93-f353364122c4

### CODE REVIEW

**Comment by kirtiraj22** [comment]
Do let me know if you need any changes, 

also, If the PR is valid then kindly use IWOC'2024 tag with relevant difficulty tag...

**Comment by ItsRoy69** [comment]
Many modifications need to be done

- Font family is a font-weight is 400 and color is rgba(0, 0, 0, 0.85)
- "Create New Account" and "Please fill out the form below. All fields are required." texts should be aligned on left and not on center
- The input boxes should have a height of "25px" , background of  "#f4f4f4" , border-radius of '12px'

- The email address input should have icon 

`
<svg xmlns="http://www.w3.org/2000/svg" width="17.501" height="15.741" viewBox="0 0 17.501 15.741"><g id="Message" transform="translate(-1.25 0.75)"><path id="Path_17585" data-name="Path 17585" d="M15.367,9.061l-3.549,2.857a1.85,1.85,0,0,1-2.285,0L5.954,9.061" transform="translate(-0.664 -4.434)" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path id="Path_17586" data-name="Path 17586" d="M6.067,3.5h7.844A4.124,4.124,0,0,1,16.89,4.823a4.174,4.174,0,0,1,1.1,3.082v5.431a4.174,4.174,0,0,1-1.1,3.082,4.124,4.124,0,0,1-2.979,1.323H6.067A4.133,4.133,0,0,1,2,13.336V7.9A4.133,4.133,0,0,1,6.067,3.5Z" transform="translate(0 -3.5)" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" fill-rule="evenodd"></path></g></svg>
`
- The username input should have icon

`
<svg xmlns="http://www.w3.org/2000/svg" width="18.317" height="20.916" viewBox="0 0 18.317 20.916"><g id="UI_icon_zap_light" data-name="UI icon/zap/light" transform="translate(-2.841 -1.542)"><path id="Union_Stroke_" data-name="Union (Stroke)" d="M8.365,20.916a3.146,3.146,0,0,1-2.529-1.321,2.889,2.889,0,0,1-.336-2.7L6.67,13.6H3.006A3,3,0,0,1,.8,8.568L7.784.986A2.9,2.9,0,0,1,9.952,0,3.146,3.146,0,0,1,12.48,1.321a2.89,2.89,0,0,1,.337,2.7l-1.17,3.29h3.664a3,3,0,0,1,2.207,5.033L10.533,19.93A2.9,2.9,0,0,1,8.365,20.916Zm1.613-18.9a.965.965,0,0,0-.723.329L2.271,9.923A1,1,0,0,0,3.006,11.6h5.08a1,1,0,0,1,.942,1.335L7.384,17.562a.964.964,0,0,0,.112.9,1.049,1.049,0,0,0,.843.44.965.965,0,0,0,.723-.329l6.985-7.582a1,1,0,0,0-.735-1.678H10.229A1,1,0,0,1,9.288,7.98l1.645-4.626a.963.963,0,0,0-.112-.9A1.049,1.049,0,0,0,9.978,2.013Z" transform="translate(2.842 1.542)" fill="#6f767e"></path></g></svg>
`

- The First and Last Name should have icon

`
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><g id="Group_3" data-name="Group 3" transform="translate(8690.5 2086)"><g id="Nav_item" data-name="Nav item" transform="translate(-8704.5 -2100)"><g id="Left" transform="translate(12 12)"><g id="UI_icon_profile_circled_light" data-name="UI icon/profile_circled/light"><g id="Vector" transform="translate(2 2)"><path id="B6568794-B5CC-4FDD-B344-1DE4E5EF7C5A" d="M4,8A4,4,0,1,1,8,4,4,4,0,0,1,4,8ZM4,2A2,2,0,1,0,6,4,2,2,0,0,0,4,2Z" transform="translate(6 4)" fill="#6f767e"></path><path id="_09760FF9-3E89-4DBD-A280-38BEDE6D663F" data-name="09760FF9-3E89-4DBD-A280-38BEDE6D663F" d="M10,20a10,10,0,1,1,6.559-2.451c-.066.057-.131.113-.2.167A10.017,10.017,0,0,1,10,20Zm0-5a4.971,4.971,0,0,0-3.964,1.95A8.009,8.009,0,0,0,9.733,18c.09,0,.168,0,.24,0H10c.078,0,.162,0,.258,0a8,8,0,0,0,3.705-1.045A4.971,4.971,0,0,0,10,15Zm0-2a6.955,6.955,0,0,1,5.563,2.75A8,8,0,1,0,2,10a7.937,7.937,0,0,0,2.438,5.75A6.952,6.952,0,0,1,10,13Z" fill="#6f767e"></path></g></g></g></g></g></svg>
`

- Password should have icon

`
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="20" viewBox="0 0 16 20"><g id="Search_input" data-name="Search input" transform="translate(-4 -2)"><g id="Left"><g id="UI_icon_lock_light" data-name="UI icon/lock/light"><path id="Union" d="M3,3.732a2,2,0,1,0-2,0V5A1,1,0,0,0,3,5Z" transform="translate(10 12)" fill="#6f767e"></path><path id="Union-2" data-name="Union" d="M13,20H3a3,3,0,0,1-3-3V9A3,3,0,0,1,3,6V5A5,5,0,1,1,13,5V6a3,3,0,0,1,3,3v8A3,3,0,0,1,13,20ZM3,8A1,1,0,0,0,2,9v8a1,1,0,0,0,1,1H13a1,1,0,0,0,1-1V9a1,1,0,0,0-1-1ZM8,2A3,3,0,0,0,5,5V6h6V5A3,3,0,0,0,8,2Z" transform="translate(4 2)" fill="#6f767e"></path></g></g></g></svg>
`

- Remove the text 'Upper Case, Lower Case, One Numbers ,8 characters'

- Give color as '#6f767e' to text aside checkbox

**Comment by kirtiraj22** [comment]
@ItsRoy69 got it!
- sorry for the inconvenience, actually there was no figma file, the only reference given was the photo and a video so it was a bit difficult to align and things up to mark. 
- Also initially I kept the text at left but it wasn't looking up to the mark so I aligned it to the center😅
- SS : 
Screenshot (297)


- But no worries I will fix all the issues and will send you a PR ASAP🫡.

**Comment by kirtiraj22** [comment]
also can you kindly clarify this : `Font family is a font-weight is 400 and color is rgba(0, 0, 0, 0.85)`
I mean should all the text should have the above mentioned font-weight and color? 
and the font family should be?

**Comment by ItsRoy69** [comment]
@kirtiraj22 ik .. sorry my bad . And the default font family is ok

**Comment by ItsRoy69** [comment]
> @ItsRoy69 got it!
> 
> * sorry for the inconvenience, actually there was no figma file, the only reference given was the photo and a video so it was a bit difficult to align and things up to mark.
> * Also initially I kept the text at left but it wasn't looking up to the mark so I aligned it to the center😅
> * SS :
>   Screenshot (297)
> * But no worries I will fix all the issues and will send you a PR ASAP🫡.

Basically you can give more space to the form side

**Comment by kirtiraj22** [comment]
@ItsRoy69 got itt!🫡

**Comment by ItsRoy69** [comment]
@kirtiraj22 once you've fixed the issues, kindly mention me on this PR

**Comment by kirtiraj22** [comment]
hey @ItsRoy69 done with the changes!

I have not changed the height and border radius of the input boxes purposely, because : 
- Height : The input boxes were looking way to small and were spoiling the UI of the page. 
Screenshot (299)

- Border radius to 12px: as we are using tailwind css, adding a custom style will make it inconsistent, so I have kept it similar. 

### Tasks completed : 
- Added all the icons(maintained a separate file for it)
- fixed the alignment of the create new account and 
- Removed the text 'Upper Case, Lower Case, One Numbers ,8 characters'
- changed color of text aside checkbox to :  '#6f767e'
- changed color of input boxes to : "#f4f4f4

kindly review the PR and if it is up to the mark then kindly use the IWOC'24 tag

also apologies for the delay!😅

**Comment by ItsRoy69** [comment]
LGTM, thanks for contributing

**Pull request merged**
