### PR TITLE
Docs: Added setup guide for backend

### PR DESCRIPTION
**Pull request by kirtiraj22**
### Changes Made
- Added a new README.md file with detailed backend setup instructions.
- Included clear and concise steps for users to follow.

Kindly review and let me know if any changes are required!

### CODE REVIEW

**Comment by kirtiraj22** [comment]
@ItsRoy69 will fix it ASAP!🫡

**Comment by kirtiraj22** [comment]
@ItsRoy69 also, By mistake I sent you the PR that resolves 2 issues ( #63 and #62 )
so can I send 2 separate PRs so that it can be a bit easy to review?

**Comment by kirtiraj22** [comment]
hey, @ItsRoy69 I have removed the validation middleware and removed all the previous changes that were causing this error.

## Current PR state : 
- [X] Contains README for backend setup and resolves (#62 )
- [X] kept `express-validator` module in package.json  (will use it to resolve #63 )

## TODO : 

- [ ] I will fix the validation bug and send a different PR for it.

**Comment by ItsRoy69** [comment]
LGTM, will be great if you now focus on express validatoe

**Pull request merged**
