### PR TITLE
Added Footer

### LINKED ISSUE #61: Create Footer
Wanna create a footer for the webpage..
can u assign  me with this issue under IWOC

### PR DESCRIPTION
**Pull request by AbhineshJha**
## Fixes #61 
Added the footer on the webpage 

image

### CODE REVIEW

**Comment by ItsRoy69** [comment]
Hey @AbhineshJha eventhough it looks good to me, but can you just make another folder inside contants folder named as  "Footer" where you can add the footer file

**Comment by ItsRoy69** [comment]
@AbhineshJha you are declaring the footer folder inside navbar folder, kindly fix it and keep the footer folder inside constants folder instead

**Comment by AbhineshJha** [comment]
sir there is already a folder named footer in constant folder..
so when i create a folder under constant 
image
 @ItsRoy69

**Comment by AbhineshJha** [comment]
Now check @ItsRoy69

**Comment by ItsRoy69** [comment]
LGTM

**Pull request merged**
