### PR TITLE
style: add hover effects to cards on home page

### PR DESCRIPTION
**Pull request by harmeetsingh11**
### Description:
This pull request addresses the static appearance of the home page cards by introducing dynamic hover effects and colored borders. The current lack of interactivity can be enhanced to improve user experience and visual aesthetics. The proposed changes aim to create a more engaging design that is consistent across both dark and light modes.

### Proposed Changes:
1. Add a subtle and visually pleasing hover effect to provide feedback to users.
2. Implement colored borders for the cards during the hover state to enhance the dynamic appearance.
3. Ensure consistent and visually appealing hover effects and colored borders in both dark and light modes.

### Screenshots/Demo

https://github.com/WikiPortal/DoodleCollab/assets/130365071/4f5d1deb-7ef0-43ab-bd97-7df8782f3d2b

### Additional Considerations:
- Test the implemented hover effects and colored borders across various devices and browsers to ensure compatibility.
- Consider user accessibility to prevent interference with the overall usability of the site.

### Expected Behavior:
- Users should experience a smooth and visually pleasing hover effect when interacting with the home page cards.
- Colored borders should enhance card visibility and provide a clear indication of the hover state.

@ItsRoy69 please review this PR.
Thanks

### CODE REVIEW

**Comment by ItsRoy69** [comment]
The shadow is becoming a bit deeper can the shadow be a bit lighter that does with the design and the animation be a bit smoother with a hover up slowly .

**Comment by harmeetsingh11** [comment]
@ItsRoy69 please review it:)

https://github.com/WikiPortal/DoodleCollab/assets/130365071/6bd8ecc9-a26e-43ac-990f-38b1fe1a67ba

**Comment by ItsRoy69** [comment]
:") the shadow needs a less vibrant and a lighter shadow

**Comment by harmeetsingh11** [comment]
@ItsRoy69 please check, I hope now its fine.

https://github.com/WikiPortal/DoodleCollab/assets/130365071/1beb7d6a-8aa5-4736-851a-7d2ff6f5079b

**Comment by ItsRoy69** [comment]
LGTM

**Pull request merged**
