### PR TITLE
Accessibility of home page  is 100% now

### PR DESCRIPTION
**Pull request by Sky-De**
###  issue #174

this pull request addresses the accessibility issue of this project ( main page ) ( #174 )

### what I have done 
I made the necessary changes to achieve the highest amount of accessibility for this application ( main page ) as you can explore in the current source code or take a look at the screenshot below

### screenshots

**BEFORE ----------------------------------------------------------------------------------------------------------------------**

Screenshot 2024-02-03 121244

**AFTER --------------------------------------------------------------------------------------------------------------------------**

Screenshot 2024-02-03 133425

### CODE REVIEW

**Comment by ItsRoy69** [comment]
@Sky-De thanks for contributing

**Comment by Sky-De** [comment]
@ItsRoy69 your welcome, is it alright with you that i apply same improvement for all pages?
Let me know
Thanks

**Comment by Sky-De** [comment]
@ItsRoy69 Hi again, I'm still looking forward to your response to my last comment as 
Is it okay with me to apply the same improvement to all pages?

1. there can be an improvement in Accessibility on the login  page
2. there can be an improvement in Accessibility on the register page
3. the theme button is oversized and does not provide any indication of its function

If you are not interested in those changes, please let me know so that I can close your project and start working on another, otherwise please inform me as soon as you can, and then I will be able to start working on those issues
thanks

**Comment by ItsRoy69** [comment]
> @ItsRoy69 You're welcome. Would you be okay with me applying the same improvement to all pages?
> 
> 1. there can be an improvement in Accessibility on the login  page
> 2. there can be an improvement in Accessibility on the register page
> 3. the theme button is oversized and does not provide any indication of its function
>    Please inform me
>    After implementing the necessary improvements, that I mentioned we can discuss making the main page responsive.
>    Thanks

sure, go for it by making another PR and issue

**Pull request merged**
