### PR TITLE
style: Hovering effects added

### LINKED ISSUE #118: 📂Other: Add hover effects to buttons and navbar links.
### What would you like to share?

There is no hover on button like on discord button on homeoage and no effects on navbar links. Add creative effects there.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

### PR DESCRIPTION
**Pull request by praptisharma28**
closes #118

### CODE REVIEW

**Comment by praptisharma28** [comment]
Check @ItsRoy69 , also please add the tags.

**Comment by ItsRoy69** [comment]
Hey @praptisharma28 its looking odd and doesn't go with design, instead will suggest to add hover effects like Civo ( https://www.civo.com/ ) the zoom in and out effect under 'trusted by developers' and the navbar color changing effects on hover

**Comment by ItsRoy69** [comment]
@praptisharma28 once done the fixations, kindly mention me on this PR

**Comment by praptisharma28** [comment]
@ItsRoy69 did it.

**Comment by ItsRoy69** [comment]
there are certain conflicts coming, can you just fix it ?

**Pull request closed without merging**
