### PR TITLE
feat: Implemented Design for Home Banner, Footer Menu, and Responsive Navbar Across All Pages

### PR DESCRIPTION
**Pull request by YashNuhash**
## **1. Improved navigation experience with a responsive Navbar.**

>**When closed** : 

image

>**When opened** : 

image

## **Responsive design updates for Home Banner.**

image

## **Enhanced responsiveness in Footer Menu.**

image

### CODE REVIEW

**Comment by YashNuhash** [comment]
@ItsRoy69 Please Review this PR

**Comment by ItsRoy69** [comment]
LGTM, thanks for contributing. That was huge PR.

**Comment by YashNuhash** [comment]
> LGTM, thanks for contributing. That was huge PR.

Can you please add the label **IWOC** for this PR?

**Comment by YashNuhash** [comment]
@ItsRoy69  In This PR the [Vercel Preview](https://doodle-collab-git-fork-yashnuhash-main-jyotirmoy-roys-projects.vercel.app/) was fine. But after merging this PR the trusted by developers section is gone break. Can you please tell me the reason why this issue is happening?

**Comment by ItsRoy69** [comment]
Merge conflict issues

**Comment by YashNuhash** [comment]
> Merge conflict issues

@ItsRoy69 
Can you please suggest me something to follow so that I can avoid merge conflict issues?

**Comment by ItsRoy69** [comment]
@YashNuhash before committing from localhost, try to git pull to keep your local codebase updated

**Pull request merged**
