### PR TITLE
Added Code of Conduct file

### LINKED ISSUE #52: CODE OF CONDUCT.md file
This repo has not any code of conduct file, so can i work on this issue under IWOC 24?

### PR DESCRIPTION
**Pull request by AbhineshJha**
**Added code of conduct file with concise description.!!**
fixes #52

### CODE REVIEW

**Comment by ItsRoy69** [comment]
LGTM

**Comment by AbhineshJha** [comment]
hey @ItsRoy69 , I think in IWOC they are increasing points on the basis of labels of prs..eg : Easy/Medium/Hard

**Comment by ItsRoy69** [comment]
did my part

**Comment by AbhineshJha** [comment]
okeh ! thankyou

**Pull request merged**
