### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by Paarisha1**
Issue number-3
I have added the dark mode to the whiteboard

### CODE REVIEW

**Comment by ItsRoy69** [comment]
Didn't understand the functionality behind creating a new file "whiteboard.jsx" .can you elaborate a bit?

**Comment by Paarisha1** [comment]
You want me to make changes in your code without adding any extra stuff?

**Comment by ItsRoy69** [comment]
I just want you to give proper name to the file like "DarkMode.jsx" or like that.. and modify the code accordingly... As by looking at the filename it becomes difficult to understand what purpose it its.

**Comment by Paarisha1** [comment]
Sure,I will change the name

**Comment by ItsRoy69** [comment]
LGTM

**Pull request merged**
