### PR TITLE
refactor:made feature page responsive for all the devices

### LINKED ISSUE #143: Website issue: Features page needs responsivness
### Description

While the features page is trying to access via mobile screens, we can see that the website is facing bugs and is not responsive

### Screenshots

image
image

image

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

### PR DESCRIPTION
**Pull request by mehedihasan2810**
closes #143

feature page is responsive now in all devices also converted inline styles into tailwind and made some minor changes

issue no. #143

### Mobile Device
mobile

### Tablet
tablet

### Desktop
desktop

### CODE REVIEW

**Comment by ItsRoy69** [comment]
there needs a white padding around the componenent as it becomes stiff

**Comment by mehedihasan2810** [comment]
hey @ItsRoy69. There is some padding around the main parent component. Are you saying to add more padding around it or between the two section? if so then for which device? I think desktop would be more appropriate

**Comment by ItsRoy69** [comment]
there needs a small space between the screen size and the blue componenent in mobile version

**Comment by ItsRoy69** [comment]
Thanks for contributing

**Comment by mehedihasan2810** [comment]
@ItsRoy69 my pleasure

**Pull request merged**
