### PR TITLE
feature : readme and workflow.md updated

### PR DESCRIPTION
**Pull request by praptisharma28**
Closes issue #4

Hey @ItsRoy69 , you can close the other 2 PRs and add this one. It has everything. 
I have made a separate workflow.md and linked it in readme. Also add the iwoc24 tag, difficulty level(medium would be appreciated as I added the contributors manually), before merging with me assigned. Thankyou for your suggestion, happy contributions !

### CODE REVIEW

**Comment by ItsRoy69** [comment]
please go through repositories like https://github.com/milancommunity/Milan , https://github.com/moja-global/community-website and follow readme styles or pattern

**Comment by praptisharma28** [comment]
Sure @ItsRoy69

**Comment by ItsRoy69** [comment]
The readme +'s position of techstacks, contributios tag is on the wrong place, linking of contribution guidelines

**Comment by praptisharma28** [comment]
@ItsRoy69 , have a look at it again. Also the links were correct earlier too, it's just that the workflow.md need to be merged first to see the file. I hope the order is right too now. I have added the license in the end and it's badge and contribution badge.

**Comment by ItsRoy69** [comment]
This looks good to me. Thanks for contributing

**Comment by praptisharma28** [comment]
@ItsRoy69 , you need to give the tag of iwoc2024 and the difficulty level before merging so that it counts on my dashboard.

**Comment by praptisharma28** [comment]
> Closes issue #4
> 
> Hey @ItsRoy69 , you can close the other 2 PRs and add this one. It has everything. I have made a separate workflow.md and linked it in readme. Also add the iwoc24 tag, difficulty level(medium would be appreciated as I added the contributors manually), before merging with me assigned. Thankyou for your suggestion, happy contributions !

@ItsRoy69 , you need to give the tag of iwoc2024 and the difficulty level before merging so that it counts on my dashboard

**Comment by ItsRoy69** [comment]
Done

**Pull request merged**
